parameters:
  - name: AdditionalMatrixReplace
    type: object
    default: []

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-native-tests.yml
    parameters:
      ServiceDirectory: storage
      Artifacts:
        - name: azure-storage-common
          groupId: com.azure
          safeName: azurestoragecommon
        - name: azure-storage-blob
          groupId: com.azure
          safeName: azurestorageblob
        - name: azure-storage-internal-avro
          groupId: com.azure
          safeName: azurestorageinternalavro
      AdditionalModules:
        - name: azure-storage-perf
          groupId: com.azure
        - name: perf-test-core
          groupId: com.azure
      TestMode: 'LIVE'
      TimeoutInMinutes: 60
      Location: canadacentral
      CloudConfig:
        Preview:
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
        PrivatePreview:
          SubscriptionConfiguration: $(sub-config-storage-test-resources)
      Clouds: Preview
      SupportedClouds: Preview
      MatrixReplace:
        # Use dedicated storage pool in canadacentral with higher memory capacity
        - Pool=(.*)-general/$1-storage
        - ${{ each additionalReplace in parameters.AdditionalMatrixReplace }}:
            - ${{ additionalReplace }}
      MatrixConfigs:
        - ${{ if contains(variables['Build.DefinitionName'], 'tests-weekly') }}:
            - Name: Storage_all_versions_live_test
              Path: sdk/storage/platform-matrix-all-versions.json
              Selection: sparse
              GenerateVMJobs: true
        - ${{ if not(contains(variables['Build.DefinitionName'], 'tests-weekly')) }}:
            - Name: Storage_live_test
              Path: sdk/storage/platform-matrix.json
              Selection: sparse
              GenerateVMJobs: true
      EnvVars:
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id)
        AZURE_CLIENT_ID: $(aad-azure-sdk-test-client-id)
        AZURE_CLIENT_SECRET: $(aad-azure-sdk-test-client-secret)
        VERSIONED_STORAGE_ACCOUNT_NAME: $(java-storage-versioned-account-name)
        VERSIONED_STORAGE_ACCOUNT_KEY: $(java-storage-versioned-account-key)
