parameters:
- name: GroupId
  type: string
  default: com.azure
- name: PackageIds
  type: object
  default: []
- name: Version
  type: string
  default: 'not-specified'
- name: BuildId
  type: number
- name: PipelineId
  type: number

variables:
  - template: /eng/pipelines/templates/variables/globals.yml
jobs:
- ${{ each artifact in parameters.PackageIds }}:
  - job: RetryOnGithubIo${{artifact.safename}}
    pool:
      name: azsdk-pool-mms-win-2019-general
      vmImage: MMS2019
    steps:
      # Sync docs repo onboarding files/folders
      - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
      - task: DownloadPipelineArtifact@2
        inputs:
          source: 'specific'
          artifact: 'packages'
          path: '$(Build.SourcesDirectory)/packages' 
          pipeline: ${{ parameters.PipelineId }}
          buildId: ${{ parameters.BuildId }}
          project: 'internal'
          RunVersion : 'specific'
      - template: /eng/common/pipelines/templates/steps/publish-blobs.yml
        parameters:
          FolderForUpload: '$(Build.SourcesDirectory)/packages/${{parameters.GroupId}}/${{artifact.name}}'
          BlobSASKey: '$(azure-sdk-docs-prod-sas)'
          BlobName: '$(azure-sdk-docs-prod-blob-name)'
          TargetLanguage: 'java'
          ArtifactLocation: $(Build.SourcesDirectory)/packages/${{parameters.GroupId}}/${{artifact.name}}
          # we override the regular script path because we have cloned the build tools repo as a separate artifact.
          ScriptPath: 'eng/common/scripts/copy-docs-to-blobstorage.ps1'

  - job: RetryOnDocsMs${{artifact.safename}}
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: MMSUbuntu20.04
    steps:
      # Sync docs repo onboarding files/folders
      - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
      - task: DownloadPipelineArtifact@2
        inputs:
          source: 'specific'
          artifact: 'packages'
          path: '$(Build.SourcesDirectory)/packages' 
          pipeline: ${{ parameters.PipelineId }}
          buildId: ${{ parameters.BuildId }}
          project: 'internal'
          RunVersion : 'specific'
      # Pull and build the docker image.
      - template: /eng/common/pipelines/templates/steps/update-docsms-metadata.yml
        parameters:
          PackageInfoLocations:
            - $(Build.SourcesDirectory)/packages/PackageInfo/${{artifact.name}}.json
          WorkingDirectory: $(System.DefaultWorkingDirectory)
          TargetDocRepoOwner: 'Azure'
          TargetDocRepoName: 'azure-docs-sdk-java'
          Language: 'java'
          SparseCheckoutPaths:
            - docs-ref-services/
            - metadata/
          DocValidationImageId: azuresdkimages.azurecr.io/javarefautocr:latest
      - template: /eng/pipelines/templates/steps/fetch-package-list.yml
        parameters:
          JavaDocJarLocation: "$(Pipeline.Workspace)/packages/${{parameters.GroupId}}/${{artifact.name}}"
          ArtifactName: ${{artifact.name}}
          TargetBranch: 'main'
          DocRepoLocation: '$(DocRepoLocation)'
          TargetDocRepoName: 'azure-docs-sdk-java'
          TargetDocRepoOwner: 'Azure'